### ISSUE TITLE
Unsupported platform: arm

### ISSUE THREAD

**Issue by kalehrl** [5ec1cff/TrickyStore#42]
I tried to install it on an arm Android TV box but the Magisk says 'Unsupported platform: arm'. Could you also compile it for armeabi-v7a?

**Comment by tryigit** [comment]
A short answer. There are many people like me who are in favor of not having it and it will make it easier to detect.
The main target is phones and in most cases the number of Android 12+ TV 32bit root users is much smaller than you think.

It also doesn't make sense to develop separate arch app 😐

**Comment by kalehrl** [comment]
I thought it was just the case of compiling it for arm 32bit which shouldn't be much of a problem. But I understand if it requires additional work that you are not willing to add it.

**Comment by PalmDevs** [comment]
It is quite literally as easy as just adding a single string to the build config, which you can't do now because the module is closed source for no clear reasons.

Some forks are still up, so you can probably make a fork of that, add the architecture (`armeabi-v7a`) to the build config and run Actions yourself.
